import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Ensure required NLTK resources are downloaded
nltk.download('punkt')
nltk.download('stopwords')

# Sample lines of text
lines_of_text = [
    '''Put a +1/+1 counter on target unit for each of your  [e].''',
    '''[Augment] Whenever you play a spell, put a +1/+1 counter on me.''',
    '''[Augment] When I despawn, create a Crystal X, where X is my defense.''',
    '''Your wisps gain +2/+1 and do not sacrifice themselves after combat. {/n}[Augment] At the end of turn, create a wisp.''',
    '''[once] When another ally with greater defense than power spawns, draw a card.''',
    '''Gain control of target unit with cost [x] or less unless its controller pays  [x].''',
    '''Sacrifice me and another ally: Delete all units with cost equal to the total number of counters on us.''',
    '''[Graft1] Put target unit with cost 2 or less from your bin into play.''',
    '''When I die, [Graft1] Delete target unit.''',
    '''When I spawn or die, [Graft1] Create a Robot 1.''',
    '''[Augment] Whenever I survive damage, put that many +1/+1 counters on me.''',
    '''Create a Poison 1 for each of your units.''',
    '''[Augment] Your other units gain +2/+2 and lose all attributes and abilities.''',
    '''[Augment][once]  [one], Erase one of my mods: I deal 2 damage to any target.''',
    '''[Graft1] Target unit gains +1/+1 for each of your units until regroup.''',
    '''[Augment] Whenever one of your units despawns, {/n}I deal 1 damage to any target.''',
    '''When another nontoken ally spawns, {/n}[Graft1] Draw a card.''',
    '''After combat, [Graft1] Each player sacrifices a unit.''',
    '''When a player loses life during battle, {/n}[Graft1] Draw a card. {i}(Damage causes life loss.)''',
    '''[Augment][once] When you play a nontoken spell, cre- {/n}ate an X/X unit, where X is the spell's cost.''',
    '''[Augment] Whenever I survive damage, each oppo- nent sacrifices that many units.''',
    '''[Graft] Target unit gains +4/+4 until regroup.''',
    '''Negate all activated and triggered effects.''',
    '''[Augment] I gain -2/-2.''',
    '''Recall X target nontoken allies. For each ally recalled this way, each player sacrifices a unit and you lose 1 life.''',
    '''I spawn with two +1/+1 counters. {/n} [Augment] When I despawn, you may move my counters onto target unit.''',
    '''[Graft1] Create three Poison 1.''',
    '''Negate target effect. Its controller gains control of me.''',
    '''[Augment] Whenever I am I dealt damage, I deal that much damage to each opponent.''',
    '''[Augment] Whenever a player loses life, put that many +1/+1 counters on me. {i}(Damage causes life loss.)''',
    '''[Graft1] Target ally and another target unit fight. {i}(They deal damage to each other equal to their power.)''',
    '''[Augment] Whenever I am dealt damage, put that many -1/-1 counters on target unit.''',
    '''When I die, [Graft] Each player sacrifices a unit.''',
    '''[Augment] Whenever my column deals combat damage to a player, put target card from that player's bin into your hand.''',
    '''Glimpse X, where X is your [b].  {i}(Reveal the top X cards of the deck and cache one. Until end of turn, you may play it as if it was in your hand, ignoring affinity. Recycle the rest.)''',
    '''Switch the power and defense of target unit until regroup.''',
    '''When my column deals combat damage,  {/n}[Graft1] Put a +1/+1 counter on each of your {/n}units.''',
    '''Each player sacrifices two units. If four or more units were sacrificed this way, repeat this.''',
    '''When you sacrifice a unit, [Graft1] Each oppo- nent sacrifices a nontoken unit.''',
    '''[Augment] When I die, create a Fireball X, where X is my power.''',
    '''[Augment] Sacrifice me: I deal 3 damage to any target. Activate this ability only if I have an adjacent ally.''',
    '''[Augment] Sacrifice another unit: I gain +2/+2 until regroup.''',
    '''Gain control of target token. You may choose new targets for spells controlled this way.''',
    '''When I attack or block,  [Graft] Target unit be- {/n}comes a base 4/4 and loses all attributes until regroup. {i}(This removes attributes from its column.)''',
    '''[Augment] Whenever a player plays a nonunit spell targeting me, they copy it and may choose new targets for the copy.''',
    '''[Augment]  [one], Remove X +1/+1 counters from me: I deal X damage to target unit.''',
    '''When you put one or more counters on an ally,  [Graft1] Draw a card.''',
    '''[Battle] Ambush  [three_blue] {i}(Play me with the effect "Recall target ally, put me into their position in play."){/i}''',
    '''[Graft1] Create a Robot X, where X is your  [m].''',
    '''Whenever a nontoken enemy dies, {/n}  [Graft] Create a 1/1 unit.''',
    '''Whenever you play a nontoken spell, {/n}[Graft] I gain +1/-1 until regroup.''',
    '''[Augment] Whenever I am modded or applied as a mod, put two +1/+1 counters on me.''',
    '''[Augment] Whenever an ally becomes the target of an enemy spell, create a 1/1 unit.''',
    '''When I attack, [Graft1] Recall up to one target unit with 5 or less defense.''',
    '''[Graft1] Create three Wisps. {i}(They are 0/1 units that can't block with "Sacrifice me after combat.")''',
    '''When I spawn, create two Shards. {i}(Dormant)''',
    '''After combat, [Graft1] You may give an opponent control of target ally. If you do, draw a card.''',
    '''[Augment] I gain +1/+1 for each other ally.''',
    '''[Augment]  [x], Sacrifice another nontoken unit: Create a Robot X. X can't be 0.''',
    '''[Augment][once] When you play a nontoken spell, cre- {/n}ate a Fireball X, where X is the spell's cost.''',
    '''Each player sacrifices half of their units, rounded up.''',
    '''[Graft1] Create an X/X unit, where X is the life target player lost in this battle. {i}(Damage causes life loss.)''',
    '''[Graft1] Glimpse 1 {i}(Reveal the top card of the deck {/n}and cache it. Until end of turn, you may play it {/n}as if it was in your hand, ignoring affinity.)''',
    '''[Augment] Sacrifice another unit: Your units gain +1/+1 until regroup.''',
    '''When you deal combat damage to an oppo- nent, if I am in your bin, recall me. {i}(Put me into your hand.)''',
    '''[Augment] After combat, create an X/X unit, where X is the number of attacking units in my formation.''',
    '''As you play a nonunit spell, you may sacrifice me. If you do, copy that spell and you may choose new targets for the copy.''',
    '''When I am dealt damage,  [Graft1] Put a +1/+1 counter on me.''',
    '''When I despawn, [Graft1] Each opponent loses 3 life.''',
    '''[Augment][two]: Create a 1/1 unit.''',
    '''When I attack or block, [Graft] Your units gain +1/+0 until regroup.''',
    '''When I die, [Graft] Rockfall 4. {i}(Each player chooses one of their units. I deal 4 damage to each of the chosen units.)''',
    '''[Augment] After combat, put a -1/-1 counter on each {/n}unit, then I deal 2 damage to each player.''',
    '''When I spawn, create two Fireball 1. {/n}[Augment] When I despawn, negate all allied spells.''',
    '''Exchange control of two target units and swap their positions.''',
    '''After combat, [Graft] Create a Robot 1.''',
    '''[Augment] Whenever a unit dies, I deal 1 damage to each opponent.''',
    '''I deal 1 damage to any target.''',
    '''[Augment] I have all abilities of adjacent allies. {/n}{i}(This includes modded abilities.)''',
    '''[Graft1] /[Put a -1/-1 counter on each enemy or{i1} put a{/n} +1/+1 counter on each of your units.]''',
    '''[Graft1] Delete target unit.''',
    '''[Augment] When my column deals combat damage to an opponent, sacrifice me. If you do, look at that player's hand and discard a card from it.''',
    '''For each player, recall target unit that {/n}player controls. {i}(Return it to their hand.)''',
    '''Negate target effect that targets an allied effect, player or unit.''',
    '''[Augment] When I die, draw a card.''',
    '''The controller of target effect may pay [one]. If they don't, negate that effect and draw a card.''',
    '''[Augment] After combat, I deal damage equal to my defense to each opponent.''',
    '''[Augment] After combat, recall me.''',
    '''When I die, you may pay [two] to recall target spell in your bin. {i}(Put it into your hand).''',
    '''Negate all other effects. For each nontoken {/n}spell negated this way, create a Fireball 1.''',
    '''Draw a card. [Graft1] Starting with you, players may play a unit from hand as if it were [Battle]. {i}(The unit's costs still need to be paid.).''',
    '''[Augment] [two]: Change a target of target effect to me.''',
    '''[Augment] Your other units gain +1/+1.''',
    '''Each player recalls two units. If four or more units were recalled this way, repeat this.''',
    '''After combat, [Graft1] Recall up to one target unit with cost less than or equal to the number of units in my formation.''',
    '''[Battle] Ambush  [4bb] {i}(Play me with the effect "Recall target ally, put me into their position in play."){/i} {/n}At the end of turn, if you took no actions during deployment,  [Graft1] Create a 3/3 unit.''',
    '''Glimpse 5 {i}(Reveal the top five cards of the deck and cache one. Until end of turn, you may play it as if it was in your hand, ignoring affinity. Recycle the rest.)''',
    '''Delete target unit. If you do, put it and {/n}all of its mods into your bin.''',
    '''When one of your units survives damage,  [Graft1] Create a 2/2 unit.''',
    '''[Augment] [once] When you play a nontoken spell, put X +1/+1 counters on me, where X is that spell's cost.''',
    '''When I attack or block, [Graft] Create a Crystal 1.''',
    '''[Augment] If one or more counters would be put on a unit by an allied source, put that many counters plus one instead.''',
    '''[Battle] Ambush  [2be] {i}(Play me with the effect "Recall target ally, put me into their position in play."){/i}  {/n}[once] When I am dealt damage, I deal that much damage to target unit.''',
    '''When I spawn, create two 1/1 units. {/n}[Augment] When I despawn, delete all token allies.''',
    '''After combat, [Graft1] Create a /[Poison {i1}or Crystal] 2.''',
    '''If you would create a Robot, Poison, Crystal or Fireball, you may instead create a token of any of these types. {i}(With the same X value.)''',
    '''[Graft1] Create a Fireball 3.''',
    '''I deal X damage to any target.''',
    '''Target unit becomes base 5/0 until regroup.''',
    '''[Augment] [once] Sacrifice X units: Create X Fireball 1.''',
    '''When the second ally dies in this battle,  [Graft1] Draw a card.''',
    '''When I attack in a formation of four or more units,  [Graft1] Draw a card.''',
    '''When I despawn, you may pay [one] to draw a card and lose 1 life.''',
    '''[Augment][once]  [one]: Negate target effect targeting me. That effect's controller draws a card.''',
    '''[Graft1] Target unit gains +7/+7 until regroup.''',
    '''When I become targeted, [Graft1] Create a Crystal 2.''',
    '''[Augment] Your units and spells gain {g}powerful. {i}(Powerful sources deal double damage).''',
    '''[Graft1] /[Sacrifice a unit]: Draw a card.''',
    '''When you create a token, [Graft1] Target ally gains +3/+3 until regroup.''',
    '''When I attack, if I am still in formation, you {/n}may put target unit with cost 2 or less from {/n}your bin into the empty slot behind me.''',
    '''[Battle] Ambush  [3bb] {i}(Play me with the effect "Recall target ally, put me into their position in play.")''',
    '''[Augment] After combat, you may recall target ally. {/n}If you do, each opponent loses 2 life.''',
    '''Reveal the top eight cards of the deck. Choose up to two of them with total cost 8 or less. You may play them now, for free. Recycle the rest.''',
    '''[Augment][once]  [one]: Switch my position with another target ally in my formation.''',
    '''Skip your draft step. When you do, draw a card. You also lose 3 life if playing a constructed format.''',
    '''[Augment] Whenever I am dealt damage, you may {/n}pay  [one]. If you do, I fight another target unit. {i}(We deal damage to each other equal to our power.)''',
    '''If I spawned this turn, other units lose all attributes and abilities during battle.''',
    '''When I attack, block, or die, [Graft1] Create two Wisps. {i}(They aren't in formation.)''',
    '''I deal 1 damage to each unit.''',
    '''[Graft1] Create a Robot 3, a Robot 2 and a Robot 1.''',
    '''[Augment] If an allied source would deal noncombat damage, it deals that much damage plus 1 instead.''',
    '''Change the targets of target effect unless its controller pays  [x].''',
    '''Recall all other spell effects and spell units. {i}(Negate them and put them into their controller's hands.)''',
    '''[Graft1] Look at target player's hand. You may choose a card from it and recycle that card. If you do, that player draws a card.''',
    '''[Augment] Spells cost  [one] more to play during battle.''',
    '''When I attack or block alone, [Graft1] Double my power and defense until regroup.''',
    '''/[Create X 1/1 units {i1}or your units become base X/X until regroup].''',
    '''When I attack or block, [Graft] Your units gain +0/+1 until regroup.''',
    '''When you play me, copy me twice. {/n}Rockfall 3 {i}(Each player chooses one of their units. {/n}I deal 3 damage to each of the chosen units.)''',
    '''Negate all enemy effects targeting allied effects, players or units.''',
    '''[Augment] When I attack or block, you may play a unit from your hand into an open position in my formation. {i}(You still pay the cost.)''',
    '''Target player reveals their hand. You choose {/n}a card from it and put it into your hand.''',
    '''[Augment] You may augment cards from hand and bin during battle as if they were  [Virus].''',
    '''[Augment] Whenever another ally spawns during battle, double its /[power {i1}or defense] until regroup.''',
    '''[Augment] Erase me: Negate all spell effects.''',
    '''You may play one unit with no abilities from your bin each deployment. {i}(Attributes are not abilities.)''',
    '''[Graft1] Exchange the base stats of two target units until regroup. {i}(With each other.)''',
    '''[Augment] Everything is {g}deadly. {i}(Any damage from a deadly source will kill a unit.)''',
    '''When I spawn or am modded, put a +1/+1 counter on each of your units. {/n}[Augment] When I despawn, remove all counters from your units.''',
    '''[Augment] Whenever a nontoken unit dies, create a 1/1 unit.''',
    '''[Graft] /[Sacrifice a unit]: Create a Poison X and a Fireball X, where X is the defense of the sacrificed unit.''',
    '''[Augment] At the end of turn, you lose 1 life and create a Poison 1.''',
    '''[Augment] Whenever one or more other cards enter a player's hand during battle, you may pay  [one] to create a 2/2 unit.''',
    '''[Augment] After combat, delete all tokens.''',
    '''I deal 2 damage to each of X target allies. For each ally damaged this way, distribute 2 damage among target opponent's units.''',
    '''[Graft] Move all counters from target unit onto another target unit.''',
    '''[Augment] Each turn, you may play a unit during the haste step as if it had  [Haste].''',
    '''[three]:   [Graft] Put a +1/+1 counter on me.''',
    '''[Augment] Your units adjacent to me gain +2/+2.''',
    '''Create a 1/1 unit for each of your [g].''',
    '''[Graft1] I deal damage to any target equal to the number of units that died in this battle.''',
    '''Negate target spell effect if its cost is less than or equal to the greatest amount of life lost by a player in this battle.''',
    '''[Augment][once] When I am dealt damage, create that many 1/1 units.''',
    '''[Augment]  [three]: Create a Robot 2.''',
    '''After combat, [Graft1] Put a +1/+1 counter on each of your units.''',
    '''[Augment] After the blocking step, I deal 1 damage to each opponent for each blocked column.''',
    '''[Graft1] Target unit gains +1/+1 and {g}piercing until regroup. {i}(Excess damage from piercing sources is dealt to the recipient's controller.)''',
    '''[Augment] When I attack or block, you and target opponent each draw a card.''',
    '''Target unit gains -2/-2 until regroup.''',
    '''[Augment] When I attack or block, create a Fireball X+1, where X is the number of allies adja- cent to me.''',
    '''[Battle] Ambush  [4bb] {i}(Play me with the effect "Recall target ally, put me into their position in play."){/i}''',
    '''[Augment] Whenever one or more -1/-1 counters are {/n}put on a unit, each opponent loses 1 life.''',
    '''When you play a nontoken spell, [Graft1] I deal 2 damage to any target.''',
    '''Target unit loses all attributes and abilities until regroup. Erase all of its mods and negate all of its effects.''',
    '''[Graft] /[Sacrifice a unit]: I deal 4 damage to any target.''',
    '''[Graft1] Target unit gains -1/-1 until regroup for each card in your hand.''',
    '''Sacrifice me: [Graft] Create a Poison 1.''',
    '''[Graft1] /[Sacrifce a unit]: Each opponent sacrifices a unit.''',
    '''When my column deals combat damage to an opponent,  [Graft1] You may sacrifice a unit. If you do, draw a card.''',
    '''[Augment] Whenever a unit token is created, put a -1/-1 counter on me. If you do, put +1/+1 counter on that token.''',
    '''[Graft1] I deal 2 damage to each of up to two target units.''',
    '''[Augment] Spells cost each player  [two] more to play {/n}for each spell their team has previously {/n}played in this battle.''',
    '''Negate target effect. Its controller Glimpses 3. {i}(They reveal the top three cards of their deck and cache one. Until end of turn, they may play it as if it was in their hand, ignoring affinity. Recycle the rest.)''',
    '''[Graft1] Create three Fireball 1.''',
    '''Sacrifice me: [Graft] Create a Fireball 1.''',
    '''[Augment] Whenever one of your units with one or more counters on it dies, you may put those counters onto another target unit.''',
    '''[Graft1] /[Remove X +1/+1 counters from allies]: I deal X damage to target unit.''',
    '''After combat, if a player lost life in this battle, create a copy of me.''',
    '''Until regroup, prevent all damage that {/n}would be dealt to target unit. Put a +1/+1 {/n}counter on it for each damage prevented {/n}this way.''',
    '''When I spawn, draw a card. {/n}[Augment] When I despawn, each other player draws two cards.''',
    '''When I attack, [Graft1] Create a Poison 5.''',
    '''[Augment] When I attack, create a 1/1 unit in my formation.''',
    '''You may play target spell from your bin until regroup. It gains {p}unstable until regroup. {i}(If it {/n}would enter a bin, erase it instead.)''',
    '''When I spawn or die, [Graft] Create a Fireball 1.''',
    '''[Augment] Abilities cost  [one] more to activate or trigger during battle. {i}(Choosing to not pay {/n}this prevents the abilities from triggering.)''',
    '''When you play a token spell, [Graft1] Target unit gains +2/+0 and {g}flying until regroup. {i}(Only flying units can block flying units.)''',
    '''[Graft1] Create an 8/8 unit.''',
    '''When my column deals combat damage to an opponent,  [Graft1][Graft1][Graft1] {i}(Trigger three copies of this graft ability as one single trigger).''',
    '''Each player gives an opponent control of one of their units. {i}(They leave formation.)''',
    '''[Augment] Whenever another ally spawns, put a +1/+1 counter on me.''',
    '''Erase target unit. Its controller Glimpses 3. {/n}{i}(They reveal the top three cards of their deck {/n}and cache one. Until end of turn, they may play it{/n} as if it was in their hand, ignoring affinity. Recycle the rest.)''',
    '''[Augment] Whenever I am dealt damage, I deal that much damage to you.''',
    '''[Graft1] Create a copy of target token.''',
    '''Negate all effects. Erase all mods.''',
    '''[Augment] Your units are base 3/3.''',
    '''I deal damage to any target equal to your [r].''',
    '''[Augment]  [x]: I become base X/X until regroup.''',
    '''[Augment] When I attack or block, create a Shard. {i}(It spawns dormant.)''',
    '''[Augment] Whenever another unit dies, put a +1/+1 counter on me.''',
    '''[Graft1] Duplicate each counter on target unit.''',
    '''Whenever I am modded, create an X/X unit, where X is the mod's cost.''',
    '''When I spawn or die, [Graft] Create a Crystal 1.''',
    '''[Augment] Your spell effects with a single target are {g}Electric. {i}(Excess damage from electric sources can {/n}be directed to an adjacent unit, recursively.)''',
    '''[Graft1] /[Sacrifice a unit]: Each opponent sacri- {/n}fices units until their total defense is at least {/n}equal to the defense of your sacrificed unit.''',
    '''Target unit gains +0/+1 until regroup. Draw a card.''',
    '''Augment target unit and all of its mods onto another target unit. {i}(The first target must have{/i}  [Augment] {i}to be able to be augmented.)''',
    '''[Augment] Spells with base cost  [three] or less have a base cost of  [three] to play during battle.''',
    '''[Augment] After combat, a player of your choice who doesn't control me gains control of me.''',
    '''[Augment] When I attack, if I am still in formation, create a 1/1 unit in all my empty adjacent slots.''',
    '''Recall target unit in your bin. {i}(Put it into your hand.)''',
    '''In this battle, you may play spells from your bin. If you do, they gain {p}unstable until regroup. {i}(If they would enter a bin, erase them instead.)''',
    '''Negate target spell effect.''',
    '''[Graft1] Each opponent discards a /[unit {i1}or spell] if {/n}able. Otherwise, they reveal their hand.''',
    '''[Augment] Sacrifice another unit: Put a +1/+1 counter on me.''',
    '''[Augment] After combat, delete all units.''',
    '''[Augment] If you would create one or more unit tokens, instead create those tokens plus an additional copy of each unique token you created.''',
    '''Erase target unit. I become an exact copy of that unit. {i}(I copy all stat changes, counters, card text and mods).''',
    '''[Graft1] Double the /[power {i1}or defense] of target unit until regroup.''',
    '''Your units gain "When I die, create a Robot 3." until regroup.''',
    '''After combat, [Graft1][Graft1] {i}(Trigger two copies of this graft ability as one single trigger.)''',
    '''When I attack or block, [Graft1] I deal damage to each player equal to the number of cards in their hand.''',
    '''[Augment]  [three]: Put a +1/+1 counter on target unit.''',
    '''When a player is dealt combat damage, {/n}[Graft1] Create a 2/2 unit.''',
    '''[Graft1] Target ally deals damage equal to its defense to another target unit.''',
    '''Two target units fight. {i}(They deal damage {/n}to each other equal to their power.)''',
    '''You may play me into an open spot in your formation.''',
    '''[Augment] Your units gain +1/+0 for each non- {/n}token spell you've played in this battle.''',
    '''[Graft1] Your units gain +2/+2 and {g}piercing until regroup. {i}(Excess damage from piercing sources is dealt to the recipient's controller.)''',
    '''When you put a counter on an enemy,  {/n}[Graft1] Draw a card.''',
    '''[Augment] Whenever you play a nontoken spell, create a 1/1 unit.''',
    '''When an enemy dies, [Graft1] Create a 2/2 unit.''',
    '''[Graft1] Create a Crystal 1 and a Poison 1.''',
    '''[Augment] Whenever one of your nontoken units dies, create a Fireball 1.''',
    '''[Graft1] Create a Robot X, where X is the greatest defense among your units.''',
    '''Delete target unit with base power 2 or less.''',
    '''[Augment] If combat damage would be dealt to you, that damage is dealt to me instead.''',
    '''At the end of turn, create a Fireball X, where X is one plus the number of spell tokens you control. {/n}[Augment] Your spell tokens stay through regroup.''',
    '''[Augment][once] When one of your spell effects deals damage, create that many 1/1 units.''',
    '''Recall target spell in your bin. {i}(Put it into your hand.)''',
    '''[Augment] When I die, put a -1/-1 counter on each unit.''',
    '''End this battle. Erase me. {i}(Negate all effects, this battle is over.)''',
    '''[Augment] After combat, sacrifice me.''',
    '''[Augment] Whenever you play a spell, I deal 1 damage to any target.''',
    '''When I die,  [Graft] Delete all units with -1/-1 counters on them.''',
    '''I deal 6 damage to target unit.''',
    '''[Augment] I gain +2/+2.''',
    '''[Graft1] Create two 1/1 units.''',
    '''[once]  [one], Recall another ally: I gain {g}flying and +2/+0 until regroup. {i}(Only flying units can block flying units.)''',
    '''When I spawn, create a Poison 6. {/n}[Augment] When I despawn, each opponent recalls a unit from their bin.''',
    '''Delete target unit with 4 or more defense.''',
    '''The controller of target enemy effect may pay  [x]. If they do, you draw a card. Otherwise, negate that effect. X can't be zero.''',
    '''[Augment] Whenever another nontoken ally spawns, create a Crystal 1.''',
    '''Draw a card.''',
    '''When another ally spawns during battle, {/n}[Graft1] I deal 2 damage to each opponent.''',
    '''I spawn with three -1/-1 counters on me. {/n}[Augment] Whenever you play a nontoken spell, you may move a counter from me onto another target unit.''',
    '''[Augment] Enemies gain +2/+2.''',
    '''[Graft1] Each player recalls a unit and loses 2 life.''',
    '''When I attack or block, [Graft] Create a Poison X, where X is my power.''',
    '''[Augment] I gain -1/-1 for each card in your hand.''',
    '''[Augment] I gain -7/-7.''',
    '''[Augment] When I attack or block, create a Robot 2 in my formation.''',
    '''[Augment] At the start of deployment, recall all your other units.''',
    '''Put a -1/-1 counter on target unit.''',
    '''Whenever you apply an augment during battle,  [Graft] I gain +2/+2 until regroup.''',
    '''I deal 6 damage to any target.''',
    '''[Augment] Whenever you play a spell during battle, each player sacrifices a unit with cost less than or equal to the spell's cost. {i}(If able.)''',
    '''[Augment] Whenever a nontoken unit dies, you may pay  [two] to erase it and put two +1/+1 counters on me.''',
    '''[Augment][once] Whenever another player plays a spell, you may exchange control of me and that spell. If you do, you may choose new targets for that spell.''',
    '''I deal 3 damage to any target.''',
    '''[Graft] Your units gain +1/+1 until regroup.''',
    '''When the second nontoken spell is played in {/n}this battle,  [Graft1] Each player recalls a unit.''',
    '''[Augment] Whenever one of your units dies, each opponent sacrifices a unit.''',
    '''[zero]:   [Graft1] Recall me. {i}(Put me into your hand.)''',
    '''[Augment] Your other units gain +0/+2.''',
    '''Target opponent negates an effect they control.''',
    '''Create a 1/1 unit for each unit in target formation.''',
    '''/[Sacrifice X units]: Negate up to X target effects.''',
    '''[Augment][once] When I am dealt damage, create an X/X unit, where X is the damage I am dealt.''',
    '''[Augment] Whenever you are dealt combat damage, target opponent gains control of me.''',
    '''[Augment] Whenever a player plays their first spell in this battle, negate it.''',
    '''[Augment] Whenever you play a unit, create a 1/1 unit.''',
    '''When I attack or block, [Graft] I deal 1 damage to each unit.''',
    '''[Augment] Whenever a card enters a player's hand {/n}during battle, I gain +2/+2 until regroup.''',
    '''After combat, gain control of target unit if it has a -1/-1 counter on it. {/n}[Augment] When I die, give each unit you control with {/n}a -1/-1 counter on it to target opponent.''',
    '''Whenever one or more other cards enter your hand during battle,  [Graft] I gain +4/+4 and {g}flying until regroup. {i}(Only flying units can block flying units.)''',
    '''[Augment] After combat, sacrifice another unit.''',
    '''[one]:   [Graft1] Give target opponent control of me. If you do, create three 1/1 units.''',
    '''[Graft1] I deal damage to target unit equal to the number of units you control.''',
    '''[Augment]  [three]: Each opponent chooses one of their units. Put a -1/-1 counter on each of the chosen units.''',
]

# Function to preprocess text
def preprocess(text):
    tokens = word_tokenize(text.lower())  # Tokenize and convert to lower case
    words = [word for word in tokens if word.isalpha()]  # Remove punctuation
    stop_words = set(stopwords.words('english'))
    filtered_words = [word for word in words if word not in stop_words]  # Remove stopwords
    return ' '.join(filtered_words)

# Preprocess each line
preprocessed_lines = [preprocess(line) for line in lines_of_text]

# Vectorize the text using TF-IDF
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(preprocessed_lines)

# Calculate cosine similarity between each pair of lines
cos_sim = cosine_similarity(tfidf_matrix)

# Function to group lines based on a similarity threshold
def group_lines(similarity_matrix, threshold=0.4):
    visited = set()
    groups = []
    for i in range(len(similarity_matrix)):
        if i not in visited:
            group = [i]
            for j in range(len(similarity_matrix)):
                if i != j and similarity_matrix[i][j] > threshold:
                    group.append(j)
                    visited.add(j)
            groups.append(group)
            visited.add(i)
    return groups

# Group the lines by similarity
groups = group_lines(cos_sim)

# Print the grouped lines
for group in groups:
    print("Group:")
    for idx in group:
        print(lines_of_text[idx].lower())
    print()