[package]
name = "algomacros"
version = "0.1.0"
edition = "2021"
authors = ["Derek Hemingson"]

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.39"
quote = "1.0"
proc-macro2 = "1.0"
